# Generated by Django 5.2.13 on 2026-04-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0007_remove_project_others_resume_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
