# Generated by Django 5.2.13 on 2026-04-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0014_alter_careerproject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerproject',
            name='introduction',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
